version: '3.9'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  omega:
    build: "server/."
    restart: always
    ports:
      - 80:80
    # volumes:
    #   - userdata:/home/CEO
      # - ./server/data/omega:/var/omega

# volumes:
#   userdata: