version: '3.9'

services:
  db:
    build: db/.
    hostname: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  omega:
    build: "server/."
    restart: always
    ports:
      - 80:80
    volumes:
      - userdata:/home/CEO
      # - ./server/data/omega:/var/omega

volumes:
  userdata:
  database: